const HookTester = require("./HookTester");
const AsyncParallelHook = require("../AsyncParallelHook");
const AsyncParallelBailHook = require("../AsyncParallelBailHook");

describe("AsyncParallelHook", () => {
	it("should have to correct behavior", async () => {
		const tester = new HookTester((args) => new AsyncParallelHook(args));

		const result = await tester.run();

		expect(result).toEqual({
			callNone: { error: 'hook.call is not a function' },
			callNoneWithArg: { error: 'hook.call is not a function' },
			callSingleSync: { error: 'hook.call is not a function' },
			callSingleSyncWithArg: { error: 'hook.call is not a function' },
			callMultipleSync: { error: 'hook.call is not a function' },
			callMultipleSyncWithArg: { error: 'hook.call is not a function' },
			callMultipleSyncWithArgs: { error: 'hook.call is not a function' },
			callMultipleSyncError: { error: 'hook.call is not a function' },
			callInspected: { error: 'hook.call is not a function' },
			callAsyncNone: { type: 'async', value: undefined },
			callAsyncNoneWithArg: { type: 'async', value: undefined },
			callAsyncSingleSyncCalled1: true,
			callAsyncSingleSync: { type: 'async', value: undefined },
			callAsyncSingleSyncWithArgCalled1: 42,
			callAsyncSingleSyncWithArg: { type: 'async', value: undefined },
			callAsyncMultipleSyncCalled1: true,
			callAsyncMultipleSyncCalled2: true,
			callAsyncMultipleSync: { type: 'async', value: undefined },
			callAsyncMultipleSyncLastReturnCalled1: true,
			callAsyncMultipleSyncLastReturnCalled2: true,
			callAsyncMultipleSyncLastReturn: { type: 'async', value: undefined },
			callAsyncMultipleSyncNoReturnCalled1: true,
			callAsyncMultipleSyncNoReturnCalled2: true,
			callAsyncMultipleSyncNoReturn: { type: 'async', value: undefined },
			callAsyncMultipleSyncWithArgCalled1: 42,
			callAsyncMultipleSyncWithArgCalled2: 42,
			callAsyncMultipleSyncWithArg: { type: 'async', value: undefined },
			callAsyncSingleAsyncWithArgCalled1: 42,
			callAsyncSingleAsyncWithArg: { type: 'async', value: undefined },
			callAsyncMultipleAsyncWithArgCalled1: 42,
			callAsyncMultipleAsyncWithArgCalled2: 42,
			callAsyncMultipleAsyncWithArg: { type: 'async', value: undefined },
			callAsyncSinglePromiseWithArgCalled1: 42,
			callAsyncSinglePromiseWithArg: { type: 'async', value: undefined },
			callAsyncMultiplePromiseWithArgCalled1: 42,
			callAsyncMultiplePromiseWithArgCalled2: 42,
			callAsyncMultiplePromiseWithArg: { type: 'async', value: undefined },
			callAsyncMultipleMixed1WithArgCalled1: 42,
			callAsyncMultipleMixed1WithArgCalled2: 42,
			callAsyncMultipleMixed1WithArgCalled3: 42,
			callAsyncMultipleMixed1WithArg: { type: 'async', value: undefined },
			callAsyncMultipleMixed2WithArgCalled1: 42,
			callAsyncMultipleMixed2WithArgCalled2: 42,
			callAsyncMultipleMixed2WithArg: { type: 'async', value: undefined },
			callAsyncMultipleMixed3WithArgCalled1: 42,
			callAsyncMultipleMixed3WithArgCalled2: 42,
			callAsyncMultipleMixed3WithArgCalled3: 42,
			callAsyncMultipleMixed3WithArg: { type: 'async', value: undefined },
			callAsyncMultipleSyncErrorCalled1: true,
			callAsyncMultipleSyncError: { type: 'async', error: 'Error in sync2' },
			callAsyncMultipleAsyncErrorCalled1: true,
			callAsyncMultipleAsyncErrorCalled3: true,
			callAsyncMultipleAsyncError: { type: 'async', error: 'Error in async2' },
			callAsyncMultipleAsyncLateErrorCalled1: true,
			callAsyncMultipleAsyncLateErrorCalled3: true,
			callAsyncMultipleAsyncLateError: { type: 'async', error: 'Error in async2' },
			callAsyncMultipleAsyncLateErrorEarlyResult1Called1: true,
			callAsyncMultipleAsyncLateErrorEarlyResult1Called3: true,
			callAsyncMultipleAsyncLateErrorEarlyResult1: { type: "async", error: "Error in async2" },
			callAsyncMultipleAsyncLateErrorEarlyResult2Called1: true,
			callAsyncMultipleAsyncLateErrorEarlyResult2Called3: true,
			callAsyncMultipleAsyncLateErrorEarlyResult2: { type: "async", error: "Error in async2" },
			callAsyncMultipleAsyncEarlyErrorCalled1: true,
			callAsyncMultipleAsyncEarlyErrorCalled3: true,
			callAsyncMultipleAsyncEarlyError: { type: 'async', error: 'Error in async2' },
			callAsyncMultiplePromiseErrorCalled1: true,
			callAsyncMultiplePromiseErrorCalled3: true,
			callAsyncMultiplePromiseError: { type: 'async', error: 'Error in async2' },
			callAsyncMultiplePromiseLateErrorCalled1: true,
			callAsyncMultiplePromiseLateErrorCalled3: true,
			callAsyncMultiplePromiseLateError: { type: 'async', error: 'Error in async2' },
			callAsyncMultiplePromiseEarlyErrorCalled1: true,
			callAsyncMultiplePromiseEarlyErrorCalled3: true,
			callAsyncMultiplePromiseEarlyError: { type: 'async', error: 'Error in async2' },
			callAsyncMultipleMixedError1WithArgCalled1: 42,
			callAsyncMultipleMixedError1WithArgCalled2: 42,
			callAsyncMultipleMixedError1WithArgCalled3: 42,
			callAsyncMultipleMixedError1WithArg: { type: 'async', error: 'Error in sync' },
			callAsyncMultipleMixedError2WithArgCalled1: 42,
			callAsyncMultipleMixedError2WithArgCalled2: 42,
			callAsyncMultipleMixedError2WithArgCalled3: 42,
			callAsyncMultipleMixedError2WithArg: { type: 'async', error: 'Error in promise' },
			callAsyncMultipleMixedError3WithArgCalled1: 42,
			callAsyncMultipleMixedError3WithArgCalled2: 42,
			callAsyncMultipleMixedError3WithArgCalled3: 42,
			callAsyncMultipleMixedError3WithArg: { type: 'async', error: 'Error in async' },
			callAsyncMultipleMixedLateErrorCalled1: true,
			callAsyncMultipleMixedLateErrorCalled2: true,
			callAsyncMultipleMixedLateErrorCalled3: true,
			callAsyncMultipleMixedLateError: { type: 'async', error: 'Error in async' },
			promiseNone: { type: 'promise', value: undefined },
			promiseNoneWithArg: { type: 'promise', value: undefined },
			promiseSingleSyncCalled1: true,
			promiseSingleSync: { type: 'promise', value: undefined },
			promiseSingleSyncWithArgCalled1: 42,
			promiseSingleSyncWithArg: { type: 'promise', value: undefined },
			promiseMultipleSyncCalled1: true,
			promiseMultipleSyncCalled2: true,
			promiseMultipleSync: { type: 'promise', value: undefined },
			promiseMultipleSyncLastReturnCalled1: true,
			promiseMultipleSyncLastReturnCalled2: true,
			promiseMultipleSyncLastReturn: { type: 'promise', value: undefined },
			promiseMultipleSyncNoReturnCalled1: true,
			promiseMultipleSyncNoReturnCalled2: true,
			promiseMultipleSyncNoReturn: { type: 'promise', value: undefined },
			promiseMultipleSyncWithArgCalled1: 42,
			promiseMultipleSyncWithArgCalled2: 42,
			promiseMultipleSyncWithArg: { type: 'promise', value: undefined },
			promiseSingleAsyncWithArgCalled1: 42,
			promiseSingleAsyncWithArg: { type: 'promise', value: undefined },
			promiseMultipleAsyncWithArgCalled1: 42,
			promiseMultipleAsyncWithArgCalled2: 42,
			promiseMultipleAsyncWithArg: { type: 'promise', value: undefined },
			promiseSinglePromiseWithArgCalled1: 42,
			promiseSinglePromiseWithArg: { type: 'promise', value: undefined },
			promiseMultiplePromiseWithArgCalled1: 42,
			promiseMultiplePromiseWithArgCalled2: 42,
			promiseMultiplePromiseWithArg: { type: 'promise', value: undefined },
			promiseMultipleMixed1WithArgCalled1: 42,
			promiseMultipleMixed1WithArgCalled2: 42,
			promiseMultipleMixed1WithArgCalled3: 42,
			promiseMultipleMixed1WithArg: { type: 'promise', value: undefined },
			promiseMultipleMixed2WithArgCalled1: 42,
			promiseMultipleMixed2WithArgCalled2: 42,
			promiseMultipleMixed2WithArg: { type: 'promise', value: undefined },
			promiseMultipleMixed3WithArgCalled1: 42,
			promiseMultipleMixed3WithArgCalled2: 42,
			promiseMultipleMixed3WithArgCalled3: 42,
			promiseMultipleMixed3WithArg: { type: 'promise', value: undefined },
			promiseMultipleSyncErrorCalled1: true,
			promiseMultipleSyncError: { type: 'promise', error: 'Error in sync2' },
			promiseMultipleAsyncErrorCalled1: true,
			promiseMultipleAsyncErrorCalled3: true,
			promiseMultipleAsyncError: { type: 'promise', error: 'Error in async2' },
			promiseMultipleAsyncLateErrorCalled1: true,
			promiseMultipleAsyncLateErrorCalled3: true,
			promiseMultipleAsyncLateError: { type: 'promise', error: 'Error in async2' },
			promiseMultipleAsyncLateErrorEarlyResult1Called1: true,
			promiseMultipleAsyncLateErrorEarlyResult1Called3: true,
			promiseMultipleAsyncLateErrorEarlyResult1: { type: 'promise', error: 'Error in async2' },
			promiseMultipleAsyncLateErrorEarlyResult2Called1: true,
			promiseMultipleAsyncLateErrorEarlyResult2Called3: true,
			promiseMultipleAsyncLateErrorEarlyResult2: { type: 'promise', error: 'Error in async2' },
			promiseMultipleAsyncEarlyErrorCalled1: true,
			promiseMultipleAsyncEarlyErrorCalled3: true,
			promiseMultipleAsyncEarlyError: { type: 'promise', error: 'Error in async2' },
			promiseMultiplePromiseErrorCalled1: true,
			promiseMultiplePromiseErrorCalled3: true,
			promiseMultiplePromiseError: { type: 'promise', error: 'Error in async2' },
			promiseMultiplePromiseLateErrorCalled1: true,
			promiseMultiplePromiseLateErrorCalled3: true,
			promiseMultiplePromiseLateError: { type: 'promise', error: 'Error in async2' },
			promiseMultiplePromiseEarlyErrorCalled1: true,
			promiseMultiplePromiseEarlyErrorCalled3: true,
			promiseMultiplePromiseEarlyError: { type: 'promise', error: 'Error in async2' },
			promiseMultipleMixedError1WithArgCalled1: 42,
			promiseMultipleMixedError1WithArgCalled2: 42,
			promiseMultipleMixedError1WithArgCalled3: 42,
			promiseMultipleMixedError1WithArg: { type: 'promise', error: 'Error in sync' },
			promiseMultipleMixedError2WithArgCalled1: 42,
			promiseMultipleMixedError2WithArgCalled2: 42,
			promiseMultipleMixedError2WithArgCalled3: 42,
			promiseMultipleMixedError2WithArg: { type: 'promise', error: 'Error in promise' },
			promiseMultipleMixedError3WithArgCalled1: 42,
			promiseMultipleMixedError3WithArg: { type: 'promise', error: 'Error in async' },
			promiseMultipleMixedLateErrorCalled1: true,
			promiseMultipleMixedLateErrorCalled2: true,
			promiseMultipleMixedLateErrorCalled3: true,
			promiseMultipleMixedLateError: { type: 'promise', error: 'Error in async' },
			callAsyncInspectedCall1: [ 1, 2, 3 ],
			callAsyncInspectedCall2: [ 1, 2, 3 ],
			callAsyncInspectedTap1: { type: 'promise', fn: 2, name: 'promise' },
			callAsyncInspectedTap2: { type: 'sync', fn: 3, name: 'sync' },
			callAsyncInspected: { type: 'async', value: undefined },
			promiseInspectedCall1: [ 1, 2, 3 ],
			promiseInspectedCall2: [ 1, 2, 3 ],
			promiseInspectedTap1: { type: 'promise', fn: 2, name: 'promise' },
			promiseInspectedTap2: { type: 'sync', fn: 3, name: 'sync' },
			promiseInspected: { type: 'promise', value: undefined }
		})
	})
})

describe("AsyncParallelBailHook", () => {
	it("should have to correct behavior", async () => {
		const tester = new HookTester((args) => new AsyncParallelBailHook(args));

		const result = await tester.run();

		expect(result).toEqual({
			callNone: { error: "hook.call is not a function" },
			callNoneWithArg: { error: "hook.call is not a function" },
			callSingleSync: { error: "hook.call is not a function" },
			callSingleSyncWithArg: { error: "hook.call is not a function" },
			callMultipleSync: { error: "hook.call is not a function" },
			callMultipleSyncWithArg: { error: "hook.call is not a function" },
			callMultipleSyncWithArgs: { error: "hook.call is not a function" },
			callMultipleSyncError: { error: "hook.call is not a function" },
			callInspected: { error: "hook.call is not a function" },
			callAsyncNone: { type: "async", value: undefined },
			callAsyncNoneWithArg: { type: "async", value: undefined },
			callAsyncSingleSyncCalled1: true,
			callAsyncSingleSync: { type: "async", value: 42 },
			callAsyncSingleSyncWithArgCalled1: 42,
			callAsyncSingleSyncWithArg: { type: "async", value: 42 },
			callAsyncMultipleSyncCalled1: true,
			callAsyncMultipleSync: { type: "async", value: 42 },
			callAsyncMultipleSyncLastReturnCalled1: true,
			callAsyncMultipleSyncLastReturnCalled2: true,
			callAsyncMultipleSyncLastReturn: { type: "async", value: 43 },
			callAsyncMultipleSyncNoReturnCalled1: true,
			callAsyncMultipleSyncNoReturnCalled2: true,
			callAsyncMultipleSyncNoReturn: { type: "async", value: undefined },
			callAsyncMultipleSyncWithArgCalled1: 42,
			callAsyncMultipleSyncWithArg: { type: "async", value: 42 },
			callAsyncSingleAsyncWithArgCalled1: 42,
			callAsyncSingleAsyncWithArg: { type: "async", value: 42 },
			callAsyncMultipleAsyncWithArgCalled1: 42,
			callAsyncMultipleAsyncWithArg: { type: "async", value: 42 },
			callAsyncSinglePromiseWithArgCalled1: 42,
			callAsyncSinglePromiseWithArg: { type: "async", value: 42 },
			callAsyncMultiplePromiseWithArgCalled1: 42,
			callAsyncMultiplePromiseWithArgCalled2: 42,
			callAsyncMultiplePromiseWithArg: { type: "async", value: 42 },
			callAsyncMultipleMixed1WithArgCalled1: 42,
			callAsyncMultipleMixed1WithArgCalled2: 42,
			callAsyncMultipleMixed1WithArgCalled3: 42,
			callAsyncMultipleMixed1WithArg: { type: "async", value: 42 },
			callAsyncMultipleMixed2WithArgCalled1: 42,
			callAsyncMultipleMixed2WithArgCalled2: 42,
			callAsyncMultipleMixed2WithArg: { type: "async", value: 42 },
			callAsyncMultipleMixed3WithArgCalled1: 42,
			callAsyncMultipleMixed3WithArgCalled2: 42,
			callAsyncMultipleMixed3WithArgCalled3: 42,
			callAsyncMultipleMixed3WithArg: { type: "async", value: 42 },
			callAsyncMultipleSyncErrorCalled1: true,
			callAsyncMultipleSyncError: { type: "async", error: "Error in sync2" },
			callAsyncMultipleAsyncErrorCalled1: true,
			callAsyncMultipleAsyncError: { type: "async", error: "Error in async2" },
			callAsyncMultipleAsyncLateErrorCalled1: true,
			callAsyncMultipleAsyncLateErrorCalled3: true,
			callAsyncMultipleAsyncLateError: { type: "async", error: "Error in async2" },
			callAsyncMultipleAsyncLateErrorEarlyResult1Called1: true,
			callAsyncMultipleAsyncLateErrorEarlyResult1Called3: true,
			callAsyncMultipleAsyncLateErrorEarlyResult1: { type: "async", error: "Error in async2" },
			callAsyncMultipleAsyncLateErrorEarlyResult2Called1: true,
			callAsyncMultipleAsyncLateErrorEarlyResult2Called3: true,
			callAsyncMultipleAsyncLateErrorEarlyResult2: { type: "async", value: 42 },
			callAsyncMultipleAsyncEarlyErrorCalled1: true,
			callAsyncMultipleAsyncEarlyError: { type: "async", error: "Error in async2" },
			callAsyncMultiplePromiseErrorCalled1: true,
			callAsyncMultiplePromiseErrorCalled3: true,
			callAsyncMultiplePromiseError: { type: "async", error: "Error in async2" },
			callAsyncMultiplePromiseLateErrorCalled1: true,
			callAsyncMultiplePromiseLateErrorCalled3: true,
			callAsyncMultiplePromiseLateError: { type: "async", error: "Error in async2" },
			callAsyncMultiplePromiseEarlyErrorCalled1: true,
			callAsyncMultiplePromiseEarlyErrorCalled3: true,
			callAsyncMultiplePromiseEarlyError: { type: "async", error: "Error in async2" },
			callAsyncMultipleMixedError1WithArgCalled1: 42,
			callAsyncMultipleMixedError1WithArgCalled2: 42,
			callAsyncMultipleMixedError1WithArgCalled3: 42,
			callAsyncMultipleMixedError1WithArg: { type: "async", value: 42 },
			callAsyncMultipleMixedError2WithArgCalled1: 42,
			callAsyncMultipleMixedError2WithArgCalled2: 42,
			callAsyncMultipleMixedError2WithArgCalled3: 42,
			callAsyncMultipleMixedError2WithArg: { type: "async", value: 42 },
			callAsyncMultipleMixedError3WithArgCalled1: 42,
			callAsyncMultipleMixedError3WithArgCalled2: 42,
			callAsyncMultipleMixedError3WithArgCalled3: 42,
			callAsyncMultipleMixedError3WithArg: { type: "async", error: "Error in async" },
			callAsyncMultipleMixedLateErrorCalled1: true,
			callAsyncMultipleMixedLateErrorCalled2: true,
			callAsyncMultipleMixedLateErrorCalled3: true,
			callAsyncMultipleMixedLateError: { type: "async", error: "Error in async" },
			promiseNone: { type: "promise", value: undefined },
			promiseNoneWithArg: { type: "promise", value: undefined },
			promiseSingleSyncCalled1: true,
			promiseSingleSync: { type: "promise", value: 42 },
			promiseSingleSyncWithArgCalled1: 42,
			promiseSingleSyncWithArg: { type: "promise", value: 42 },
			promiseMultipleSyncCalled1: true,
			promiseMultipleSync: { type: "promise", value: 42 },
			promiseMultipleSyncLastReturnCalled1: true,
			promiseMultipleSyncLastReturnCalled2: true,
			promiseMultipleSyncLastReturn: { type: "promise", value: 43 },
			promiseMultipleSyncNoReturnCalled1: true,
			promiseMultipleSyncNoReturnCalled2: true,
			promiseMultipleSyncNoReturn: { type: "promise", value: undefined },
			promiseMultipleSyncWithArgCalled1: 42,
			promiseMultipleSyncWithArg: { type: "promise", value: 42 },
			promiseSingleAsyncWithArgCalled1: 42,
			promiseSingleAsyncWithArg: { type: "promise", value: 42 },
			promiseMultipleAsyncWithArgCalled1: 42,
			promiseMultipleAsyncWithArg: { type: "promise", value: 42 },
			promiseSinglePromiseWithArgCalled1: 42,
			promiseSinglePromiseWithArg: { type: "promise", value: 42 },
			promiseMultiplePromiseWithArgCalled1: 42,
			promiseMultiplePromiseWithArgCalled2: 42,
			promiseMultiplePromiseWithArg: { type: "promise", value: 42 },
			promiseMultipleMixed1WithArgCalled1: 42,
			promiseMultipleMixed1WithArgCalled2: 42,
			promiseMultipleMixed1WithArgCalled3: 42,
			promiseMultipleMixed1WithArg: { type: "promise", value: 42 },
			promiseMultipleMixed2WithArgCalled1: 42,
			promiseMultipleMixed2WithArgCalled2: 42,
			promiseMultipleMixed2WithArg: { type: "promise", value: 42 },
			promiseMultipleMixed3WithArgCalled1: 42,
			promiseMultipleMixed3WithArgCalled2: 42,
			promiseMultipleMixed3WithArgCalled3: 42,
			promiseMultipleMixed3WithArg: { type: "promise", value: 42 },
			promiseMultipleSyncErrorCalled1: true,
			promiseMultipleSyncError: { type: "promise", error: "Error in sync2" },
			promiseMultipleAsyncErrorCalled1: true,
			promiseMultipleAsyncError: { type: "promise", error: "Error in async2" },
			promiseMultipleAsyncLateErrorCalled1: true,
			promiseMultipleAsyncLateErrorCalled3: true,
			promiseMultipleAsyncLateError: { type: "promise", error: "Error in async2" },
			promiseMultipleAsyncLateErrorEarlyResult1Called1: true,
			promiseMultipleAsyncLateErrorEarlyResult1Called3: true,
			promiseMultipleAsyncLateErrorEarlyResult1: { type: 'promise', error: 'Error in async2' },
			promiseMultipleAsyncLateErrorEarlyResult2Called1: true,
			promiseMultipleAsyncLateErrorEarlyResult2Called3: true,
			promiseMultipleAsyncLateErrorEarlyResult2: { type: 'promise', value: 42 },
			promiseMultipleAsyncEarlyErrorCalled1: true,
			promiseMultipleAsyncEarlyError: { type: "promise", error: "Error in async2" },
			promiseMultiplePromiseErrorCalled1: true,
			promiseMultiplePromiseErrorCalled3: true,
			promiseMultiplePromiseError: { type: "promise", error: "Error in async2" },
			promiseMultiplePromiseLateErrorCalled1: true,
			promiseMultiplePromiseLateErrorCalled3: true,
			promiseMultiplePromiseLateError: { type: "promise", error: "Error in async2" },
			promiseMultiplePromiseEarlyErrorCalled1: true,
			promiseMultiplePromiseEarlyErrorCalled3: true,
			promiseMultiplePromiseEarlyError: { type: "promise", error: "Error in async2" },
			promiseMultipleMixedError1WithArgCalled1: 42,
			promiseMultipleMixedError1WithArgCalled2: 42,
			promiseMultipleMixedError1WithArgCalled3: 42,
			promiseMultipleMixedError1WithArg: { type: "promise", value: 42 },
			promiseMultipleMixedError2WithArgCalled1: 42,
			promiseMultipleMixedError2WithArgCalled2: 42,
			promiseMultipleMixedError2WithArgCalled3: 42,
			promiseMultipleMixedError2WithArg: { type: "promise", value: 42 },
			promiseMultipleMixedError3WithArgCalled1: 42,
			promiseMultipleMixedError3WithArgCalled2: 42,
			promiseMultipleMixedError3WithArgCalled3: 42,
			promiseMultipleMixedError3WithArg: { type: "promise", error: "Error in async" },
			promiseMultipleMixedLateErrorCalled1: true,
			promiseMultipleMixedLateErrorCalled2: true,
			promiseMultipleMixedLateErrorCalled3: true,
			promiseMultipleMixedLateError: { type: "promise", error: "Error in async" },
			callAsyncInspectedCall1: [1, 2, 3],
			callAsyncInspectedTap1: { fn: 2, name: "promise", type: "promise" },
			callAsyncInspectedCall2: [1, 2, 3],
			callAsyncInspectedTap2: { fn: 3, name: "sync", type: "sync" },
			callAsyncInspected: { type: "async", value: 6 },
			promiseInspectedCall1: [1, 2, 3],
			promiseInspectedTap1: { fn: 2, name: "promise", type: "promise" },
			promiseInspectedCall2: [1, 2, 3],
			promiseInspectedTap2: { fn: 3, name: "sync", type: "sync" },
			promiseInspected: { type: "promise", value: 6 },
		})
	})
})
